# Generated by Django 6.0.3 on 2026-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
    ]
