# Generated by Django 6.0.3 on 2026-04-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=20)),
                ('Worker_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=30)),
            ],
        ),
    ]
